### ISSUE TITLE
Off-Hand itemization for Fury and Enha random bots are missing.

### ISSUE THREAD

**Issue by Thatharis** [liyunfan1223/mod-playerbots#579] opened 2024-10-05 23:07 UTC
**Describe the bug**
random Enha Shammy and Fury Warr bots are really bad at gearing their off-hands. On lvl 60 at least. They will most of the time choose shields or one handed weapons for their off hand and after the raid, Fury Warrs will even unequip their off-handed two-hander and will revert back to just using a single two-handed weapon. I've even seen Enha shammies run around with held-in off-hand items.

**Commit hash**
4fc9bca

**Expected behavior**
Fury Warriors should be itemized to always have TWO Two-handed weapons while Enha Shammies should have an extra one-handed weapon for their off-hand, preferrably something hard hitting unlike Rogue off-hands to benefit from their abilities that hit with both weapons.

**Screenshots**
![WoWScrnShot_100624_020329](https://github.com/user-attachments/assets/24c45140-8b39-424b-9904-79d6fe972784)
Oitchen here has a Spinal Reaper he earned from his Ragnaros kill, however he does not equip it alongside his default lvl 60 weapon, which was the Gavel of Qiraji Authority.
![WoWScrnShot_100624_020339](https://github.com/user-attachments/assets/ce3fcb6e-5e85-4c83-a610-a1ae6d1a7c77)
Aitso hasn't gotten any new weapons from raids yet, however this does not stop her from rolling need on shields to get as an off-hander. She should have an off-hand weapon at lvl 60.

**Desktop (please complete the following information):**
 - Debian
 - Browser: Chrome
 - Version 12

**Comment by Mr-Deadbeat** [comment] 2024-10-06 10:16
i know the feeling it's a bit frustrating i've made sure my Alt characters can't equip items "random world drops" because the bots equip pretty much anything they can get their hands on so BOE items most of the time end up useless since once used they are pretty much vendor trash also bots roll on items they should not roll for AT all for example plate wearing warriors rolling on healer plate or plate suitable for retribution paladins or god forbid they roll on cloth these are a few examples the other character classes tend to behave the same way leather wearers rolling for cloth and so on

i hope it will be fixed eventually but for the moment turn off autogearing and do things manually only way to keep your sanity ;)

**Comment by Bobblybook** [comment] 2024-11-06 13:40
I've had a look into this, I believe the issue is with how bots currently equip gear/upgrades in `ItemUsageValue.cpp`.

A WorldPacket with opcode `CMSG_AUTOEQUIP_ITEM` is used. This is effectively a right-click style equip.. the problem here is any equipment slot which has more than one slot (rings, trinkets, weapons), only the first slot will be equipped/upgraded.

When a bot has no item in the second slot, it will often be filled with whatever the first eligible right-clickable item is for that slot, and then never upgraded again.

I have been testing code to identify upgrades for the second slot. This part I seem to have working, however I can't figure out a way to ask the bot to equip it in the second slot.

The above opcode doesn't allow for specifying this, we may need to use a different equipping method or maybe a diff opcode. There is one called `CMSG_AUTOEQUIP_ITEM_SLOT`, but I don't think it's for equipping to a gear slot but rather something to do with the bag slot of the item in inventory.

There is a manual way of equipping item (that you can find in the opcode handler) that is not a good idea to re-implement.. if can find out what opcode the client sends when you manually equip an item on your character in the second slot, we can probably implement this.

**Closed** 2024-11-07 16:19 UTC
Labels: bug, enhancement, priority: Medium
