### ISSUE TITLE
New Crash

### ISSUE THREAD

**Issue by htc16** [liyunfan1223/mod-playerbots#70] opened 2023-11-27 21:53 UTC
Hello,
I'm using the latest version, and after 4 days online the server failed.

[gdb.txt](https://github.com/liyunfan1223/mod-playerbots/files/13480750/gdb.txt)

EDIT
I had another crash a few hours after the last one above.

[gdb.txt](https://github.com/liyunfan1223/mod-playerbots/files/13488501/gdb.txt)

**Comment by Jinxlynx** [comment] 2023-11-27 22:39
Shit mine goes down no more then 5 hours

**Comment by rogerc66** [comment] 2023-11-28 02:18
mine might last a day and half.

**Comment by Jinxlynx** [comment] 2023-11-28 02:24
My issue seems to always happen when they encounter open world pvp like 3v3 the server just freezes up usually following a crash sometimes an account gets stuck attacking casting channel and has to be deleted from db for server to be able to come back online. And then I get hard crash at 5-6 hours. I'd have to check my logs but looks the same as the other 2 crash reports.

**Comment by evrydayjunglist** [comment] 2023-11-28 16:51
Do you have any other modules installed? I found that mod-gain-honor-guard caused my server to crash consistently. Since removing I don't have crashes, but I generally only leave it up for ~24 hours. I will try to leave it up for multiple days.

**Comment by Jinxlynx** [comment] 2023-12-04 22:58
> Do you have any other modules installed? I found that mod-gain-honor-guard caused my server to crash consistently. Since removing I don't have crashes, but I generally only leave it up for ~24 hours. I will try to leave it up for multiple days.

Actually yeah that did cause my issue. Kinda weird. But. Now I got OPs crash after a 24-96 hours.

**Comment by liyunfan1223** [comment] 2023-12-05 02:08
I'm also having a crash on my server that I've been working on for a long time. Unfortunately, I cannot reproduce such crash stably and it seems to be a probabilistic event. The crash also occured after an undetermined period of time on mine. Thank all of you for your efforts and the information and logs provided, it is very helpful in resolving the issue.

By the way, sorry for the late reply. I've been working on other things the past few weeks.

**Comment by zbhcn** [comment] 2023-12-05 05:27
try this code to creat the crash dmp file：

    //启动全局异常捕获生成dump
    AC::DumpHelper::SetIsDumpCrash(true);
    //设置dump文件保存目录
    AC::DumpHelper::SetDumpDirectory("dmp");
    //设置最大dump文件数，超过会自动删除最旧的文件
    AC::DumpHelper::SetDumpMaxFileCount(30);
    //触发一个异常
    AC::DumpHelper::Snapshot("current.dmp");

**Comment by liyunfan1223** [comment] 2023-12-23 16:54
A few crashes were discovered and resolved, and it should last longer :). Please try updating to the latest version.

**Closed as completed** 2023-12-23 18:17 UTC
Labels: Bug
