### ISSUE TITLE
Random LFG Bug

### ISSUE THREAD

**Issue by FizCap** [liyunfan1223/mod-playerbots#587] opened 2024-10-08 18:33 UTC
**Describe the bug**
The bots leave the dungeon party as soon as it starts everytime for me

**Commit hash**
10/7 update

**Screenshots**
(https://www.youtube.com/watch?v=2VgONgrTcvs)

**Desktop (please complete the following information):**
Windows 10

**Additional context**

**Comment by EricksOliveira** [comment] 2024-10-08 18:37
Confirmed.

**Comment by cptcl** [comment] 2024-10-13 16:33
This bug is around for a long time. Hope it gets fixed in the future.

**Comment by EricksOliveira** [comment] 2024-10-13 22:59
I did some tests and the problem seems to be related to the Bots' response time. I made some changes regarding this and managed to resolve it. Also improved response time in PvP and PvE for Bots. I'm only testing memory consumption, which appears to be normal. But it needs to be tested more calmly. I'll be doing a PR so we can test together.

**Comment by EricksOliveira** [comment] 2024-10-13 23:19
https://github.com/liyunfan1223/mod-playerbots/pull/602

**Comment by EricksOliveira** [comment] 2024-10-17 11:02
any news? After the updates this problem was resolved for me.

**Comment by FizCap** [comment] 2024-10-19 15:49
I still I had the error, joined a random lfg and 2 bots left

**Comment by mw108** [comment] 2024-10-24 04:56
Confirmed. Ran a few dungeons and everything was ok. Just got in a dungeon where the DD bot left immediately.

![image](https://github.com/user-attachments/assets/b0e4ea13-f77a-438f-9e1f-51a1aaa66f86)

**Comment by Mr-Deadbeat** [comment] 2024-10-26 04:56
have the same issues but from my findings trying to join a random dungeon run as a Tank caused the most issues took forever to find a group also the bots decline most of the time or the timer runs out going to close down my issue i created since this has been created long before mine ;)

also this is still an ongoing problem worked fine before the patch mentioned above the problems seem to have been introduced sometime after the patch have not played for a long time so hence not noticed the issues until now

**Comment by EricksOliveira** [comment] 2024-11-05 14:01
https://github.com/liyunfan1223/mod-playerbots/pull/681

**Closed** 2024-11-18 22:23 UTC
Labels: bug, priority: Medium
