### ISSUE TITLE
Old problem

### ISSUE THREAD

**Issue by htc16** [liyunfan1223/mod-playerbots#5] opened 2023-06-20 22:08 UTC
This is an old problem, which is a little annoying.

https://github.com/ZhengPeiRu21/mod-playerbots/issues/121

**Comment by liyunfan1223** [comment] 2023-06-21 05:59
Not sure if this issue is caused by mod, or is it also present in the original Azerothcore.

**Comment by Blandyoung** [comment] 2023-08-26 17:32
> 兄弟，我发现了问题所在，请打电话给我 Discord 以便我向您展示？
May I ask what the problem is? I would like to try to fix it

**Comment by Blandyoung** [comment] 2023-08-26 17:33
> Bro @liyunfan1223 , I found out where the problem is, call me on Discord so I can show you?

May I ask what the problem is? I would like to try to fix it

**Comment by Dreathean** [comment] 2023-09-15 12:21
@htc16 were you able to get this resolved with liyunfan?

**Comment by Dreathean** [comment] 2024-06-06 13:44
Should this be closed?

**Closed** 2024-06-12 16:35 UTC
