### ISSUE TITLE
Server crash 

### ISSUE THREAD

**Issue by davvvve1** [liyunfan1223/mod-playerbots#754] opened 2024-12-01 19:08 UTC
**Describe the bug**
Crash 

**Commit hash**
latest this day 1/12

**To Reproduce**
1. Go to auctionhous and spam dungs

**Expected behavior**
When i stand in Orgrimmar in auction house and spam Dungeons , When the dungeon is over server crash after Dungen when you are tp back it should work

**Screenshots**

**Desktop (please complete the following information):**
Debian 12

**Additional context**

**Comment by noisiver** [comment] 2024-12-01 19:14
Need a crash log to determine the cause. Without it, it's impossible to find and even less possible to fix the issue.

**Comment by davvvve1** [comment] 2024-12-01 23:46
Gonna fix that after work. Thank u

**Comment by Dreathean** [comment] 2024-12-16 17:53
Closing due to no crash logs as requested after 2 weeks, please re-open if you are still experiencing this issue with crash logs on latest commit

**Closed by Dreathean** 2024-12-16 17:53 UTC

**Comment by Povotech** [comment] 2025-02-19 22:34
the server does not stay online for more than 20 minutes without crashing, I just let the world run to see and the server crashes, I have no crash log the file is empty, it is generated well at the time of the crash but 0 data

**Comment by PaoloBenigni** [comment] 2025-02-20 02:19
Have you tried gbd?
