### ISSUE TITLE
Crash - SearchForBestPath

### ISSUE THREAD

**Issue by serverwar** [liyunfan1223/mod-playerbots#478] opened 2024-08-14 21:08 UTC
[1cc4836d8210+_worldserver.exe_[14-8_16-59-4].txt](https://github.com/user-attachments/files/16618878/1cc4836d8210%2B_worldserver.exe_.14-8_16-59-4.txt)
I worked hard to identify this error, I put extra log to catch error at the right point, and I saw that the SearchForBestPath function is receiving null value for x and y, after receiving the null value the server crashed server.log last information. @liyunfan1223 

![image](https://github.com/user-attachments/assets/b949b4d0-8ccf-483d-9d36-ffc8bcef0542)

**Comment by serverwar** [comment] 2024-08-14 22:39
A new crash after updates 
[1cc4836d8210+_worldserver.exe_[14-8_18-58-58].txt](https://github.com/user-attachments/files/16619579/1cc4836d8210%2B_worldserver.exe_.14-8_18-58-58.txt)

**Comment by noisiver** [comment] 2024-08-14 22:41
Looks like a crash caused by `ChatReplyAction`. Maybe @atidot3 knows why this is happening and can or is possibly already working on a fix?

*Always disabling chat myself I hope I don't run into this*

**Comment by atidot3** [comment] 2024-08-14 22:47
Hmmm where do you see its from charreplyaction ?
PlayerbotAI.cpp line 1067 seems related to knockback :
bot->GetMotionMaster()->MoveKnockbackFromForPlayer(bot->GetPositionX() + vcos, bot->GetPositionY() + vsin,
                                                               horizontalSpeed, verticalSpeed);

**Comment by noisiver** [comment] 2024-08-14 22:50
I was just about to mention the second crash report. I figured you were working on something for this, I seem to remember something being mentioned on Discord.

I guess disabling chat would stop it from crashing until you're done with that PR. We don't want you to rush it out just to deal with that crash.

**Comment by atidot3** [comment] 2024-08-14 22:51
Thing is it depends on people computers, with small amount of bots or high etc, its a complicated one as HEAP is allocation on the stack witch occures everywhere

**Comment by noisiver** [comment] 2024-08-14 22:53
Yes but to clarify, if people are having crashes from this - would disabling chat stop it from crashing until it's been sorted out? It's good to know what to tell people (even though it's a temporary thing) if people start asking about crashes like this one.

**Comment by atidot3** [comment] 2024-08-14 22:55
It should help for sure to disable it

**Comment by serverwar** [comment] 2024-08-19 20:07
[1cc4836d8210+_worldserver.exe_[19-8_2-38-22].txt](https://github.com/user-attachments/files/16664811/1cc4836d8210%2B_worldserver.exe_.19-8_2-38-22.txt)
New crash @liyunfan1223

**Comment by serverwar** [comment] 2024-08-23 17:47
[f357e051decc+_worldserver.exe_[23-8_13-17-50].txt](https://github.com/user-attachments/files/16732125/f357e051decc%2B_worldserver.exe_.23-8_13-17-50.txt)
Hey, is it okay if you can pay attention to this error?  @liyunfan1223

**Comment by serverwar** [comment] 2024-08-25 05:58
![image](https://github.com/user-attachments/assets/d1a86826-844
[1cc4836d8210+_worldserver.exe_[24-8_19-57-58].txt](https://github.com/user-attachments/files/16739158/1cc4836d8210%2B_worldserver.exe_.24-8_19-57-58.txt)
4-4b24-8e16-c8c95010799a)
There is more space in this part, I got it right and the crash stopped.

**Comment by liyunfan1223** [comment] 2024-08-25 11:29
> [1cc4836d8210+_worldserver.exe_[19-8_2-38-22].txt](https://github.com/user-attachments/files/16664811/1cc4836d8210%2B_worldserver.exe_.19-8_2-38-22.txt) New crash @liyunfan1223

Fixed. https://github.com/liyunfan1223/mod-playerbots/pull/491

**Comment by liyunfan1223** [comment] 2024-08-25 11:30
> [f357e051decc+_worldserver.exe_[23-8_13-17-50].txt](https://github.com/user-attachments/files/16732125/f357e051decc%2B_worldserver.exe_.23-8_13-17-50.txt) Hey, is it okay if you can pay attention to this error? @liyunfan1223

Might be fixed but not sure. https://github.com/liyunfan1223/mod-playerbots/pull/491

**Comment by serverwar** [comment] 2024-08-30 16:11
After updating, there are only 2 crashes that register in my logs, the second one is the one that gets in the way the most.
[9dbe5070ebea+_worldserver.exe_[29-8_22-34-0].txt](https://github.com/user-attachments/files/16819639/9dbe5070ebea%2B_worldserver.exe_.29-8_22-34-0.txt) -1


[9dbe5070ebea+_worldserver.exe_[29-8_19-58-7].txt](https://github.com/user-attachments/files/16819641/9dbe5070ebea%2B_worldserver.exe_.29-8_19-58-7.txt) -2 @liyunfan1223

**Comment by serverwar** [comment] 2024-08-31 17:46
> Não estou muito surpreso que você esteja tendo certos problemas se estiver usando Eluna com Playerbots.
I have a lot of players exploring it, errors happen without it, because I already took it out to test

**Comment by serverwar** [comment] 2024-08-31 17:46
> I'm not super surprised you're having certain issues if you're using Eluna with Playerbots.

I have a lot of players exploring it, errors happen without it, because I already took it out to test

**Comment by serverwar** [comment] 2024-08-31 17:49
[9dbe5070ebea+_worldserver.exe_[31-8_11-14-34].txt](https://github.com/user-attachments/files/16825557/9dbe5070ebea%2B_worldserver.exe_.31-8_11-14-34.txt)

**Comment by serverwar** [comment] 2024-09-01 05:05
[9dbe5070ebea+_worldserver.exe_[1-9_1-49-7].txt](https://github.com/user-attachments/files/16827378/9dbe5070ebea%2B_worldserver.exe_.1-9_1-49-7.txt) - @liyunfan1223

**Comment by serverwar** [comment] 2024-09-06 16:51
> [9dbe5070ebea+_worldserver.exe_[1-9_1-49-7].txt](https://github.com/user-attachments/files/16827378/9dbe5070ebea%2B_worldserver.exe_.1-9_1-49-7.txt) - @liyunfan1223

Can you help me with this crash?

**Comment by liyunfan1223** [comment] 2024-09-07 05:12
https://github.com/liyunfan1223/mod-playerbots/commit/87978d6cd8f6b01c2aea9345484054bead1365d1 I hope they are fixed now. Just curious, how do you run the server? Some of the crash conditions seem pretty rare to me.

**Comment by serverwar** [comment] 2024-09-07 06:11
> [87978d6](https://github.com/liyunfan1223/mod-playerbots/commit/87978d6cd8f6b01c2aea9345484054bead1365d1) I hope they are fixed now. Just curious, how do you run the server? Some of the crash conditions seem pretty rare to me.

My server is on a dedicated 128 ram 40 cores, windows 2022 server, I only use customization in eluna engine but there are very few, crossfaction module, ahbot, transmog and 1x1.

**Comment by serverwar** [comment] 2024-09-10 22:15
@liyunfan1223 2 days without any crash, one question is sometimes the server freezes for 5 seconds and comes back, or the update goes up for a long time online generating a 1 second delay, is there anything I can do to monitor what is generating these high loads.

**Comment by serverwar** [comment] 2024-09-12 04:17
[ad42ec6c5583_worldserver.exe_[11-9_21-37-6].txt](https://github.com/user-attachments/files/16973355/ad42ec6c5583_worldserver.exe_.11-9_21-37-6.txt)
[ad42ec6c5583_worldserver.exe_[11-9_12-18-0].txt](https://github.com/user-attachments/files/16973356/ad42ec6c5583_worldserver.exe_.11-9_12-18-0.txt) It's much more stable, today 2 new crashes appeared, after 2 days without anything @liyunfan1223

**Comment by serverwar** [comment] 2024-09-12 20:48
> @liyunfan1223 2 days without any crash, one question is sometimes the server freezes for 5 seconds and comes back, or the update goes up for a long time online generating a 1 second delay, is there anything I can do to monitor what is generating these high loads.

![image](https://github.com/user-attachments/assets/4ab152cb-e1fe-4684-8236-3a35538c5d6e)

**Comment by serverwar** [comment] 2024-09-13 04:05
> [ad42ec6c5583_worldserver.exe_[11-9_21-37-6].txt](https://github.com/user-attachments/files/16973355/ad42ec6c5583_worldserver.exe_.11-9_21-37-6.txt) [ad42ec6c5583_worldserver.exe_[11-9_12-18-0].txt](https://github.com/user-attachments/files/16973356/ad42ec6c5583_worldserver.exe_.11-9_12-18-0.txt) It's much more stable, today 2 new crashes appeared, after 2 days without anything @liyunfan1223

**Comment by serverwar** [comment] 2024-09-13 04:07
[ad42ec6c5583_worldserver.exe_[12-9_22-16-7].txt](https://github.com/user-attachments/files/16988370/ad42ec6c5583_worldserver.exe_.12-9_22-16-7.txt) @liyunfan1223 
If you can look at these 3 crash logs, it helps me a lot, it's 1 different per day, eliminating it will be 1000%

**Comment by serverwar** [comment] 2024-09-26 18:57
Most of this has already been fixed, I'll close this one

**Closed** 2024-09-26 18:57 UTC
Labels: bug
