### ISSUE TITLE
[AI] Obsidian Sanctum

### ISSUE THREAD

**Issue by blinkysc** [liyunfan1223/mod-playerbots#691] opened 2024-11-06 18:59 UTC
Bots should use portal with Shadron

Additionally, bots don't dodge waves of lava with Sartharion (though even crap armor they do fine)

Not sure how well with 3D

**Comment by noisiver** [comment] 2024-11-06 19:29
They don't have **any** strategies for the raid so however well you can micromanage them is how well they'll do. Dodging the lava is easy to manage but three drakes would be tough without enough gear to eat through the boss. They need proper strategies to do it as intended, and I'm sure eventually there will be. It all depends on if anyone feels like coding them, I guess.

**Comment by blinkysc** [comment] 2024-12-02 04:10
New commit might change this. I haven’t checked it out yet

**Comment by Bobblybook** [comment] 2024-12-02 09:23
This should be somewhat fixed with #752 

It's not perfect, especially with offtank behaviour, but lava waves and void zones should work, as well as portal.

I've noticed the dmg reduction debuff applied to sarth appears to be buggy and sometimes doesn't apply.
The bots use this as a trigger to zone through the portal, so if you see them not jumping in despite the acolyte being alive, this is likely why.

3D is not implemented, that fight is quite a bit more complex and requires a different strat.

The strategy for 2D should also function for 1D and 0D, as mentioned it needs improving but it should work to actually kill the boss now.

**Closed** 2024-12-02 09:24 UTC
Labels: enhancement, priority: Medium
