### ISSUE TITLE
Giving a bot the command to cast a spell crashes the server

### ISSUE THREAD

**Issue by ghost** [liyunfan1223/mod-playerbots#345] opened 2024-07-15 14:15 UTC
Bug: Giving a bot the command to cast a spell crashes the servers - server restarts. Tested with a mage-bot and various spells. Tested with unbot gui and via whisper commands.

AzerothCore rev. 05c9a96ba99c 2024-07-11 (Playerbot branch) (Unix, Release, Static)

I went back to a version prior to the recent update, and there the issue does not happen (AzerothCore rev. fb4dbdd60491 2024-06-24 (Playerbot branch) (Unix, Release, Static)

**Comment by vr-jan** [comment] 2024-07-16 20:28
i have the same issue: 
- casting from the bots spellbook (unbot)
- casting with @mage cast polymorph, or @warlock cast immolate , ....
( when the bots cast themselves, automatically there seems to be no problem: only when given the order to)

it worked a few days ago without issues (100% sure), but i applied the updates from the last 3 - 5 days (core + playerbotmod); ever since then i have the issue.

**Comment by vr-jan** [comment] 2024-07-16 21:03
LFG Queue check finished
BG Queue check finished
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 4294967296) > this->size() (which is 3)
Caught signal 6
Segmentation fault (core dumped)

**Comment by dr-kosmos** [comment] 2024-07-17 00:28
It's related to changes made in CastCustomSpellAction.cpp, 266aa1ec888c9589d4d47cd57da7faa515e91898
Tested by reverting those changes in my fork.

**Comment by liyunfan1223** [comment] 2024-07-17 08:24
It should be fixed by the latest commit https://github.com/liyunfan1223/mod-playerbots/pull/353, please comfirm.

**Comment by vr-jan** [comment] 2024-07-17 08:35
fix confirmed, thank you

**Closed** 2024-07-17 09:34 UTC
Labels: bug
