### ISSUE TITLE
Server crashing

### ISSUE THREAD

**Issue by serverwar** [liyunfan1223/mod-playerbots#321] opened 2024-07-11 00:48 UTC
After the latest updates, the server has been crashing. I can't reproduce the issue, but I can provide data about the crash.
[Crash.txt](https://github.com/user-attachments/files/16170161/Crash.txt)
[crash3.txt](https://github.com/user-attachments/files/16170182/crash3.txt)
[crash4.txt](https://github.com/user-attachments/files/16170183/crash4.txt)
[crash2.txt](https://github.com/user-attachments/files/16170184/crash2.txt)

**Comment by Jgoodwin64** [comment] 2024-07-11 02:56
Mine too.

**Comment by fuzzdeveloper** [comment] 2024-07-11 07:24
@serverwar there's been a fair few commits recently, what commit hash are you on (**git log -1** then copy the stuff right of "commit") need that so I can line up those logs with the version you're running (note only valid if you havent updated since those logs).

**Comment by serverwar** [comment] 2024-07-16 00:11
I updated the version today and the crash went to 1, I'll leave the log here.
[36280c72520f_worldserver.exe_[15-7_20-32-42].txt](https://github.com/user-attachments/files/16241486/36280c72520f_worldserver.exe_.15-7_20-32-42.txt)
I just use your version, with some basic modules

**Comment by fuzzdeveloper** [comment] 2024-07-16 04:42
That's a different issue to the one you observed earlier, I've experienced both myself, the earlier crashes (which would vary in exact place that ACCESS_VIOLATION happened but it always involved a call to PlayerbotAI::HasAuraToDispel()) appear to be fixed now.

This one (containing call to AvoidAoeAction::AvoidAuraWithDynamicObj()) is a newer problem (and your new stacktrace is identical to the one I had too). I think liyun's aware of the issue (judging from comments in the code of that method) so will probably have a fix soon, you can avoid the crash for now by setting AiPlayerbot.AutoAvoidAoe = 0.

**Comment by serverwar** [comment] 2024-07-16 05:01
[36280c72520f_worldserver.exe_[15-7_22-58-50].txt](https://github.com/user-attachments/files/16243341/36280c72520f_worldserver.exe_.15-7_22-58-50.txt)
[36280c72520f_worldserver.exe_[15-7_22-19-15].txt](https://github.com/user-attachments/files/16243342/36280c72520f_worldserver.exe_.15-7_22-19-15.txt)
Thanks for the work, I'll post 2 more that happened

**Comment by liyunfan1223** [comment] 2024-07-17 13:22
> After I update the latest fixes, the update continues to crash. [36280c72520f_worldserver.exe_[16-7_21-55-28].txt](https://github.com/user-attachments/files/16258050/36280c72520f_worldserver.exe_.16-7_21-55-28.txt) [36280c72520f_worldserver.exe_[16-7_22-4-58].txt](https://github.com/user-attachments/files/16258051/36280c72520f_worldserver.exe_.16-7_22-4-58.txt)

These two crashes should be fixed in https://github.com/liyunfan1223/mod-playerbots/pull/354. Please comfirm with the latest commit.

**Comment by serverwar** [comment] 2024-07-17 15:06
> > After I update the latest fixes, the update continues to crash. [36280c72520f_worldserver.exe_[16-7_21-55-28].txt](https://github.com/user-attachments/files/16258050/36280c72520f_worldserver.exe_.16-7_21-55-28.txt) [36280c72520f_worldserver.exe_[16-7_22-4-58].txt](https://github.com/user-attachments/files/16258051/36280c72520f_worldserver.exe_.16-7_22-4-58.txt)
> 
> These two crashes should be fixed in #354. Please comfirm with the latest commit.

Thank you, I've already updated the version, it's online, I'll let you know later if it worked.

**Comment by serverwar** [comment] 2024-07-17 16:15
[36280c72520f_worldserver.exe_[17-7_11-58-29].txt](https://github.com/user-attachments/files/16269384/36280c72520f_worldserver.exe_.17-7_11-58-29.txt)
After today's update

**Comment by serverwar** [comment] 2024-07-18 03:01
> > After I update the latest fixes, the update continues to crash. [36280c72520f_worldserver.exe_[16-7_21-55-28].txt](https://github.com/user-attachments/files/16258050/36280c72520f_worldserver.exe_.16-7_21-55-28.txt) [36280c72520f_worldserver.exe_[16-7_22-4-58].txt](https://github.com/user-attachments/files/16258051/36280c72520f_worldserver.exe_.16-7_22-4-58.txt)
> 
> These two crashes should be fixed in #354. Please comfirm with the latest commit.

These crashes didn't happen anymore, just the last one I posted

**Comment by serverwar** [comment] 2024-07-18 05:01
[c586134f9f50_worldserver.exe_[18-7_1-39-46].txt](https://github.com/user-attachments/files/16277808/c586134f9f50_worldserver.exe_.18-7_1-39-46.txt)
More after 7 hours online

**Comment by serverwar** [comment] 2024-07-22 15:13
After the last updates, the server was online for 2 days and 11 hours, running bg and raids, I will leave my last crash record and I will update the source today and check the corrections. 
[c586134f9f50_worldserver.exe_[21-7_12-50-23].txt](https://github.com/user-attachments/files/16336001/c586134f9f50_worldserver.exe_.21-7_12-50-23.txt)

**Comment by serverwar** [comment] 2024-07-22 23:12
[c586134f9f50+_worldserver.exe_[22-7_19-52-4].txt](https://github.com/user-attachments/files/16340528/c586134f9f50%2B_worldserver.exe_.22-7_19-52-4.txt)
[c586134f9f50+_worldserver.exe_[22-7_19-55-31].txt](https://github.com/user-attachments/files/16340529/c586134f9f50%2B_worldserver.exe_.22-7_19-55-31.txt)
[c586134f9f50+_worldserver.exe_[22-7_20-1-8].txt](https://github.com/user-attachments/files/16340530/c586134f9f50%2B_worldserver.exe_.22-7_20-1-8.txt)
[c586134f9f50+_worldserver.exe_[22-7_20-7-19].txt](https://github.com/user-attachments/files/16340531/c586134f9f50%2B_worldserver.exe_.22-7_20-7-19.txt)
Too many falls now

**Comment by serverwar** [comment] 2024-07-23 00:08
[c586134f9f50+_worldserver.exe_[22-7_20-1-8].txt](https://github.com/user-attachments/files/16340913/c586134f9f50%2B_worldserver.exe_.22-7_20-1-8.txt)
[c586134f9f50+_worldserver.exe_[22-7_20-7-19].txt](https://github.com/user-attachments/files/16340914/c586134f9f50%2B_worldserver.exe_.22-7_20-7-19.txt)
[c586134f9f50+_worldserver.exe_[22-7_19-52-4].txt](https://github.com/user-attachments/files/16340915/c586134f9f50%2B_worldserver.exe_.22-7_19-52-4.txt)
[c586134f9f50+_worldserver.exe_[22-7_19-55-31].txt](https://github.com/user-attachments/files/16340916/c586134f9f50%2B_worldserver.exe_.22-7_19-55-31.txt)
Now there are a lot of falls.

**Comment by serverwar** [comment] 2024-07-24 05:29
> [c586134f9f50+_worldserver.exe_[22-7_20-1-8].txt](https://github.com/user-attachments/files/16340913/c586134f9f50%2B_worldserver.exe_.22-7_20-1-8.txt) [c586134f9f50+_ ](https://github.com/user-attachments/files/16340914/c586134f9f50%2B_worldserver.exe_.22-7_20-7-19.txt)[c586134f9f50+_worldserver.exe_[23-7_14-59-9].txt](https://github.com/user-attachments/files/16352822/c586134f9f50%2B_worldserver.exe_.23-7_14-59-9.txt) worldserver.exe_[22-7_20-7-19].txt [c586134f9f50+_worldserver.exe_[22-7_19-52-4].txt](https://github.com/user-attachments/files/16340915/c586134f9f50%2B_worldserver.exe_.22-7_19-52-4.txt) [c586134f9f50+_worldserver.exe_[22-7_19-55-31].txt](https://github.com/user-attachments/files/16340916/c586134f9f50%2B_worldserver.exe_.22-7_19-55-31.txt) Now there are a lot of falls. [c586134f9f50+_worldserver.exe_[23-7_16-20-25].txt](https://github.com/user-attachments/files/16353553/c586134f9f50%2B_worldserver.exe_.23-7_16-20-25.txt)
> 
> [c586134f9f50+_worldserver.exe_[23-7_14-59-9].txt](https://github.com/user-attachments/files/16352834/c586134f9f50%2B_worldserver.exe_.23-7_14-59-9.txt)<<<< https://youtu.be/pLN-SfluDTY

**Comment by serverwar** [comment] 2024-07-24 05:31
https://youtu.be/pLN-SfluDTY  ----
[c586134f9f50+_worldserver.exe_[23-7_16-20-25].txt](https://github.com/user-attachments/files/16357600/c586134f9f50%2B_worldserver.exe_.23-7_16-20-25.txt)

**Comment by serverwar** [comment] 2024-07-25 18:33
> [c586134f9f50+ _worldserver.exe_ [22-7_20-1-8].txt ](https://github.com/user-attachments/files/16340913/c586134f9f50%2B_worldserver.exe_.22-7_20-1-8.txt) [c586134f9f50+_ ](https://github.com/user-attachments/files/16340914/c586134f9f50%2B_worldserver.exe_.22-7_20-7-19.txt)[c586134f9f50+ _worldserver.exe_ [23-7_14-59-9].txt](https://github.com/user-attachments/files/16352822/c586134f9f50%2B_worldserver.exe_.23-7_14-59-9.txt) worldserver.exe_[22-7_20-7-19].txt [c586134f9f50+ _worldserver.exe_ [22-7_19-52-4].txt ](https://github.com/user-attachments/files/16340915/c586134f9f50%2B_worldserver.exe_.22-7_19-52-4.txt) [c586134f9f50+ _worldserver.exe_ [22-7_19-55-31].txt](https://github.com/user-attachments/files/16340916/c586134f9f50%2B_worldserver.exe_.22-7_19-55-31.txt) Agora há muitas quedas. [c586134f9f50+ _worldserver.exe_ [23-7_16-20-25].txt](https://github.com/user-attachments/files/16353553/c586134f9f50%2B_worldserver.exe_.23-7_16-20-25.txt) What is causing a crash in this log, this achievement ID 12618, after removing it from the player, the server stopped crashing
> 
> [c586134f9f50+ _worldserver.exe_ [23-7_14-59-9].txt](https://github.com/user-attachments/files/16352834/c586134f9f50%2B_worldserver.exe_.23-7_14-59-9.txt)

**Comment by serverwar** [comment] 2024-07-25 22:43
After the updates of the 25th 
[d99a248fa43f+_worldserver.exe_[25-7_19-23-31].txt](https://github.com/user-attachments/files/16384280/d99a248fa43f%2B_worldserver.exe_.25-7_19-23-31.txt)

**Comment by serverwar** [comment] 2024-07-28 05:01
Could you pay attention to this crash, the only one that still bothers me?
[237c6d846458+_worldserver.exe_[26-7_22-48-55].txt](https://github.com/user-attachments/files/16402254/237c6d846458%2B_worldserver.exe_.26-7_22-48-55.txt)

**Comment by liyunfan1223** [comment] 2024-07-28 05:18
> Could you look at this crash, the only one that still bothers me? [237c6d846458+_worldserver.exe_[26-7_22-48-55].txt](https://github.com/user-attachments/files/16402254/237c6d846458%2B_worldserver.exe_.26-7_22-48-55.txt)

This should be caused by a battleground that is not fully implemented. Currently only warsong, arathi and alterac can ensure correct. Do you know which battleground fight is this crash occurred on? I can't get it from the log you provided.

**Comment by serverwar** [comment] 2024-07-28 06:31
> > Could you look at this crash, the only one that still bothers me? [237c6d846458+_worldserver.exe_[26-7_22-48-55].txt](https://github.com/user-attachments/files/16402254/237c6d846458%2B_worldserver.exe_.26-7_22-48-55.txt)
> 
> This should be caused by a battleground that is not fully implemented. Currently only warsong, arathi and alterac can ensure correct. Do you know which battleground fight is this crash occurred on? I can't get it from the log you provided.

I don't know yet which battlefield is taking place, I will monitor the battlgrounds and let you know.

**Comment by serverwar** [comment] 2024-08-04 17:34
[f618444e30cb_worldserver.exe_[4-8_11-44-55].txt](https://github.com/user-attachments/files/16488413/f618444e30cb_worldserver.exe_.4-8_11-44-55.txt)
[f618444e30cb_worldserver.exe_[4-8_14-27-53].txt](https://github.com/user-attachments/files/16488414/f618444e30cb_worldserver.exe_.4-8_14-27-53.txt)
![image](https://github.com/user-attachments/assets/9c82deaa-5ee6-4dcb-9313-c9739d9f28b5)  I removed all the battlegrounds that do not have bots implemented and the error still persists, I am currently experiencing 2 crashes.

**Comment by serverwar** [comment] 2024-08-08 07:36
> [f618444e30cb_worldserver.exe_[4-8_11-44-55].txt](https://github.com/user-attachments/files/16488413/f618444e30cb_worldserver.exe_.4-8_11-44-55.txt) [f618444e30cb_worldserver.exe_[4-8_14-27-53].txt](https://github.com/user-attachments/files/16488414/f618444e30cb_worldserver.exe_.4-8_14-27-53.txt) ![image](https://private-user-images.githubusercontent.com/65511189/354918797-9c82deaa-5ee6-4dcb-9313-c9739d9f28b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMDI3NjgsIm5iZiI6MTcyMzEwMjQ2OCwicGF0aCI6Ii82NTUxMTE4OS8zNTQ5MTg3OTctOWM4MmRlYWEtNWVlNi00ZGNiLTkzMTMtYzk3MzlkOWYyOGI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDA3MzQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0ZjAyMjM5MzgwNTM0MTI2NDdhZTI4Nzc5Y2JkN2ZlZWM3OWE0YzAwNTZmMmRiZTUwZjFjODllZmI4NjMzODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Yya3miUQzMpBjER_c6bpAfbRbypOgWiBGGAbJ1lv-ug) I removed all the battlegrounds that do not have bots implemented and the error still persists, I am currently experiencing 2 crashes. @liyunfan1223

X: 664
Y: 668
Z: 672 
Digging deeper into the logs I found more or less where the crash occurs
X: 640
Y: 644
Z: 648

**Closed** 2024-08-14 21:00 UTC
Labels: bug
