### ISSUE TITLE
Alterac

### ISSUE THREAD

**Issue by Nansydrew** [liyunfan1223/mod-playerbots#266] opened 2024-06-09 09:26 UTC
On the battlefield alterac valley NPC bots just gather in a bunch near the cemetery capture flag and try to capture it

**Comment by Dreathean** [comment] 2024-06-09 14:43
This is noted in https://github.com/liyunfan1223/mod-playerbots/issues/69

**Comment by Dreathean** [comment] 2024-06-12 15:04
Closing as duplicate of https://github.com/liyunfan1223/mod-playerbots/issues/69

**Closed by Dreathean** 2024-06-12 15:04 UTC
