### ISSUE TITLE
Value "online" of table "characters" in "acore_characters" is not set to 0 when going offline

### ISSUE THREAD

**Issue by locchi93** [liyunfan1223/mod-playerbots#746] opened 2024-11-29 11:31 UTC
**Describe the bug**
Value "online" of table "characters" in "acore_characters" is not set to 0 when going offline. This problem is also present on any alts added with ".playerbot bot add XXX" (I don't use randombot so I can't say if the problem is there too). I think this bug has been around for a while now, I don't know if it's from the azerothcore repo fork or the mod itself but it definitely wasn't on the official azerothcore repo when I tried it a while ago.

**Commit hash**
[3e449fff731fd79bfc1fc5e5f8abd1f23ea81ac8](https://github.com/liyunfan1223/mod-playerbots/commit/3e449fff731fd79bfc1fc5e5f8abd1f23ea81ac8)

**To Reproduce**
1. Startup server.
2. Open client and go online with a character (ex. Bob).
3. Go offline with the same character.
4. Check the column "online" of table "characters" in "acore_characters" db (SELECT name,online FROM characters WHERE name="Bob";).
5. Reported value for online is still 1 and will be set to 0 only if the server is restarted.

**Expected behavior**
Value of column "online" of table "characters" in "acore_characters" is set to 0 when going offline. 

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04.1 server

**Additional context**
Docker installation

**Comment by noisiver** [comment] 2024-11-29 11:57
Duplicate of https://github.com/liyunfan1223/mod-playerbots/issues/710

**Closed** 2024-11-30 16:04 UTC
